# Generated by Django 2.0.3 on 2018-03-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sex', models.TextField(null=True)),
                ('pub_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
