# Generated by Django 2.0.3 on 2018-03-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_tourgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourgroup',
            name='content_url',
            field=models.CharField(max_length=32),
        ),
    ]
