# Generated by Django 2.0.3 on 2018-03-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20180329_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourgroup',
            name='content_url',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='tourgroup',
            name='picture',
            field=models.CharField(max_length=64),
        ),
    ]
