# Generated by Django 2.0.3 on 2018-03-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20180329_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourgroup',
            name='content_url',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='tourgroup',
            name='picture',
            field=models.CharField(max_length=128),
        ),
    ]
