# Generated by Django 2.0.3 on 2018-04-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20180331_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('desc', models.TextField(null=True)),
                ('content_url', models.CharField(max_length=256)),
                ('picture', models.CharField(max_length=128)),
                ('pub_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
