# Generated by Django 2.0.3 on 2018-04-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headprotrait_url',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.TextField(),
        ),
    ]
