# Generated by Django 2.0.3 on 2018-04-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headprotrait_url',
            field=models.CharField(blank=True, default='http://193.112.86.91/1.jpg', max_length=128),
        ),
    ]
