# Generated by Django 2.0.3 on 2018-05-28 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_usernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=32)),
                ('content', models.CharField(max_length=256)),
                ('headprotrait_url', models.CharField(blank=True, default='http://193.112.86.91/1.jpg', max_length=128)),
                ('pub_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.User')),
            ],
        ),
    ]
