# Generated by Django 2.0.3 on 2018-12-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_auto_20180528_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuanJing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content_url', models.CharField(max_length=256)),
                ('picture', models.CharField(max_length=128)),
                ('pub_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
